---
# file: roles/fedora/tasks/main.yml

- name: add Vivaldi web browser yum repo
  yum_repository:
    name: 'vivaldi'
    description: 'Vivaldi browser repository'
    baseurl: 'http://repo.vivaldi.com/archive/rpm/x86_64'
    gpgkey: 'http://repo.vivaldi.com/archive/linux_signing_key.pub'
  become: yes
  become_user: root

- name: add Brave web browser yum repo
  yum_repository:
    name: 'brave'
    description: 'Brave browser repository'
    baseurl: 'https://brave-browser-rpm-release.s3.brave.com/x86_64/'
    gpgkey: 'https://brave-browser-rpm-release.s3.brave.com/brave-core.asc'
  become: yes
  become_user: root

- name: install the rpmfusion repo packages
  dnf:
    name: 'http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm'
    state: present
  become: yes
  become_user: root

- name: install the rpmfusion repo packages
  dnf:
    name: 'http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm'
    state: present
  become: yes
  become_user: root

- name: update system
  dnf:
    name: '*'
    state: latest
  become: yes
  become_user: root

- name: install common packages
  dnf:
    name: "{{ packages['common'] }}"
    state: latest
  become: true
  become_user: root

- name: install msttcorefonts
  dnf:
    name: 'https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm'
    state: present
  become: yes
  become_user: root

- name: make Gnome/Git keyring integration helper
  command: git config --global credential.helper /usr/libexec/git-core/git-credential-gnome-keyring
