---
# roles/ubuntu/vars/main.yml

repos:
  xenial:
    - { name: 'adapta', url: 'ppa:tista/adapta' }
    - { name: 'ansible', url: 'ppa:ansible/ansible' }
    - { name: 'audacity', url: 'ppa:ubuntuhandbook1/audacity' }
    - { name: 'chkservice', url: 'ppa:linuxenko/chkservice' }
    - { name: 'dvdstyler', url: 'ppa:ubuntuhandbook1/dvdstyler' }
#    - { name: 'cinnamon', url: 'ppa:embrosyn/cinnamon' }
    - { name: 'hipchat4', url: 'deb https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client {{ ansible_distribution_release }} main' }
    - { name: 'libreoffice', url: 'ppa:libreoffice/ppa' }
    - { name: 'noobslab-icons', url: 'ppa:noobslab/icons' }
    - { name: 'noobslab-themes', url: 'ppa:noobslab/themes' }
    - { name: 'numix', url: 'ppa:numix/ppa' }
    - { name: 'obs-studio', url: 'ppa:obsproject/obs-studio' }
    - { name: 'system76', url: 'ppa:system76-dev/stable' }
    - { name: 'vivaldi', url: 'deb http://repo.vivaldi.com/stable/deb/ stable main' }
    - { name: 'webupd8', url: 'ppa:nilarimogard/webupd8' }
    - { name: 'webupd8team-atom', url: 'ppa:webupd8team/atom' }
    - { name: 'webupd8team-java', url: 'ppa:webupd8team/java' }
    - { name: 'google-chrome', url: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' }
#    { name: 'gnome3-staging', url: 'ppa:gnome3-team/gnome3-staging' }
#    { name: 'gnome3', url: 'ppa:gnome3-team/gnome3' }
  zesty:
    - { name: 'adapta', url: 'ppa:tista/adapta' }
    - { name: 'ansible', url: 'ppa:ansible/ansible' }
    - { name: 'audacity', url: 'ppa:ubuntuhandbook1/audacity' }
    - { name: 'chkservice', url: 'ppa:linuxenko/chkservice' }
    - { name: 'darktable', url: 'ppa:pmjdebruijn/darktable-release' }
    - { name: 'dvdstyler', url: 'ppa:ubuntuhandbook1/dvdstyler' }
    # - { name: 'cinnamon', url: 'ppa:embrosyn/cinnamon' }
    # - { name: 'hipchat4', url: 'deb https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client {{ ansible_distribution_release }} main' }
    - { name: 'libreoffice', url: 'ppa:libreoffice/ppa' }
    - { name: 'noobslab-icons', url: 'ppa:noobslab/icons' }
    - { name: 'noobslab-themes', url: 'ppa:noobslab/themes' }
    - { name: 'numix', url: 'ppa:numix/ppa' }
    - { name: 'system76', url: 'ppa:system76-dev/stable' }
    - { name: 'vivaldi', url: 'deb http://repo.vivaldi.com/stable/deb/ stable main' }
    - { name: 'webupd8', url: 'ppa:nilarimogard/webupd8' }
    - { name: 'webupd8team-atom', url: 'ppa:webupd8team/atom' }
    - { name: 'webupd8team-java', url: 'ppa:webupd8team/java' }
    - { name: 'google-chrome', url: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' }
#    { name: 'gnome3-staging', url: 'ppa:gnome3-team/gnome3-staging' }
#    { name: 'gnome3', url: 'ppa:gnome3-team/gnome3' }
  artful:
    - { name: 'adapta', url: 'ppa:tista/adapta' }
    - { name: 'ansible', url: 'ppa:ansible/ansible' }
    - { name: 'audacity', url: 'ppa:ubuntuhandbook1/audacity' }
    - { name: 'darktable', url: 'ppa:pmjdebruijn/darktable-release' }
    - { name: 'dvdstyler', url: 'ppa:ubuntuhandbook1/dvdstyler' }
    # - { name: 'cinnamon', url: 'ppa:embrosyn/cinnamon' }
    # - { name: 'hipchat4', url: 'deb https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client {{ ansible_distribution_release }} main' }
    # - { name: 'hipchat4', url: 'deb https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client zesty main' }
    - { name: 'kubuntu', url: 'ppa:kubuntu-ppa/backports' }
    - { name: 'libreoffice', url: 'ppa:libreoffice/ppa' }
    - { name: 'linuxuprising', url: 'ppa:linuxuprising/java' }
    - { name: 'noobslab-icons', url: 'ppa:noobslab/icons' }
    - { name: 'noobslab-themes', url: 'ppa:noobslab/themes' }
    - { name: 'numix', url: 'ppa:numix/ppa' }
    - { name: 'obs-studio', url: 'ppa:obsproject/obs-studio' }
    - { name: 'system76', url: 'ppa:system76-dev/stable' }
    - { name: 'vivaldi', url: 'deb http://repo.vivaldi.com/stable/deb/ stable main' }
    - { name: 'webupd8', url: 'ppa:nilarimogard/webupd8' }
    - { name: 'webupd8team-atom', url: 'ppa:webupd8team/atom' }
    - { name: 'webupd8team-java', url: 'ppa:webupd8team/java' }
    - { name: 'google-chrome', url: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' }
#    { name: 'gnome3-staging', url: 'ppa:gnome3-team/gnome3-staging' }
#    { name: 'gnome3', url: 'ppa:gnome3-team/gnome3' }
  bionic:
    - { name: 'adapta', url: 'ppa:tista/adapta' }
    - { name: 'ansible', url: 'ppa:ansible/ansible' }
    - { name: 'audacity', url: 'ppa:ubuntuhandbook1/audacity' }
    - { name: 'darktable', url: 'ppa:pmjdebruijn/darktable-release' }
    - { name: 'dvdstyler', url: 'ppa:ubuntuhandbook1/dvdstyler' }
    # - { name: 'cinnamon', url: 'ppa:embrosyn/cinnamon' }
    # - { name: 'hipchat4', url: 'deb https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client {{ ansible_distribution_release }} main' }
    # - { name: 'hipchat4', url: 'deb https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client zesty main' }
    - { name: 'kubuntu', url: 'ppa:kubuntu-ppa/backports' }
    - { name: 'libreoffice', url: 'ppa:libreoffice/ppa' }
    - { name: 'linuxuprising', url: 'ppa:linuxuprising/java' }
    - { name: 'noobslab-icons', url: 'ppa:noobslab/icons' }
    - { name: 'noobslab-themes', url: 'ppa:noobslab/themes' }
    - { name: 'numix', url: 'ppa:numix/ppa' }
    - { name: 'obs-studio', url: 'ppa:obsproject/obs-studio' }
    - { name: 'system76', url: 'ppa:system76-dev/stable' }
    - { name: 'vivaldi', url: 'deb http://repo.vivaldi.com/stable/deb/ stable main' }
    - { name: 'webupd8', url: 'ppa:nilarimogard/webupd8' }
    - { name: 'webupd8team-atom', url: 'ppa:webupd8team/atom' }
    - { name: 'webupd8team-java', url: 'ppa:webupd8team/java' }
    - { name: 'google-chrome', url: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' }
#    { name: 'gnome3-staging', url: 'ppa:gnome3-team/gnome3-staging' }
#    { name: 'gnome3', url: 'ppa:gnome3-team/gnome3' }
  disco:
#    - { name: 'adapta', url: 'ppa:tista/adapta' }
#    - { name: 'ansible', url: 'ppa:ansible/ansible' }
#    - { name: 'audacity', url: 'ppa:ubuntuhandbook1/audacity' }
#    - { name: 'darktable', url: 'ppa:pmjdebruijn/darktable-release' }
#    - { name: 'dvdstyler', url: 'ppa:ubuntuhandbook1/dvdstyler' }
    - { name: 'kubuntu', url: 'ppa:kubuntu-ppa/backports' }
    - { name: 'libreoffice', url: 'ppa:libreoffice/ppa' }
#    - { name: 'noobslab-icons', url: 'ppa:noobslab/icons' }
#    - { name: 'noobslab-themes', url: 'ppa:noobslab/themes' }
    - { name: 'obs-studio', url: 'ppa:obsproject/obs-studio' }
    - { name: 'system76', url: 'ppa:system76-dev/stable' }
#    - { name: 'webupd8', url: 'ppa:nilarimogard/webupd8' }
#    - { name: 'webupd8team-atom', url: 'ppa:webupd8team/atom' }
  eoan:
    - { name: 'ansible', url: 'ppa:ansible/ansible' }
#    - { name: 'system76', url: 'ppa:system76-dev/stable' }
#    - { name: 'darktable', url: 'ppa:pmjdebruijn/darktable-release' }
#    - { name: 'dvdstyler', url: 'ppa:ubuntuhandbook1/dvdstyler' }

packages:
  common:
    - apt-rdepends
    - audacity
    - backintime-gnome
    - bleachbit
    - build-essential
    - cheese
    - cifs-utils
    - compizconfig-settings-manager
    - curl
    - darktable
    - debconf-utils
    - dia
    - emacs
    - evolution
    - evolution-ews
    - evolution-indicator
    - evolution-plugins
    - evolution-plugins-experimental
    - evolution-rss
    - ffmpeg
    - filezilla
    - font-manager
    - fonts-cantarell
    - fonts-century-catalogue
    - fonts-crosextra-caladea
    - fonts-crosextra-carlito
    - fonts-gfs*
    - fonts-sil-gentium*
    - git
    - git-core
    - git-doc
    - glabels
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-ugly
    - gvfs-fuse
    - htop
    - inkscape
    - iotop
    - libreoffice
#    - libgnome-keyring-dev
    - libxss1
    - meld
    - multitail
    - openssh-server
    - p7zip-full
    - plank
    - ppa-purge
    - psgml
#    - pytagsfs
    - python-dev
    - python-mode
    - scribus
    - synaptic
    - system76-driver
    - thunderbird
    - ubuntu-restricted-extras
    - vim
    - vlc
    - vorbisgain
  xenial:
  #   - cairo-dock
  #   - cairo-dock-plug-ins
    - chkservice
#    - cinnamon-desktop-environment
    - flashplugin-installer
    - fontconfig-infinality
    - fonts-droid
    - gpointing-device-settings
  #   - 'playonlinux'
  #   - 'typecatcher'
    - obs-studio
    - oomox
    - virtualbox-5.1
  zesty: 
    - account-plugin-linkedin
    - alien
    - chkservice
    - gpointing-device-settings
    - oomox
    - virtualbox-5.1
  artful: 
    - alien
    - obs-studio
    # - oomox
    - virtualbox
  bionic: 
    - alien
    - obs-studio
    - virtualbox
  disco:
    - net-tool
    - obs-studio
    - virtualbox
  eoan:
    - cinnamon-desktop-environment
    - mate-desktop-environment
    - mate-desktop-environment-extras
    - mate-applet-appmenu
    - virtualbox
