---
# file: roles/java/tasks/main.yml

- name: download OpenJ9 JDK 11
  get_url:
    url: 'http://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/OpenJDK11U-jdk_x64_linux_openj9_linuxXL_11.0.5_10_openj9-0.17.0.tar.gz'
    dest: "{{ ansible_env.HOME }}/Downloads/OpenJDK11U-jdk_x64_linux_openj9_linuxXL_11.0.5_10_openj9-0.17.0.tar.gz"

- name: unpack OpenJ9 JDK 11
  unarchive:
    src: "{{ ansible_env.HOME }}/Downloads/OpenJDK11U-jdk_x64_linux_openj9_linuxXL_11.0.5_10_openj9-0.17.0.tar.gz"
    dest: /opt/
    remote_src: yes
    creates: /opt/jdk-11.0.3+7/
  become: yes
  become_user: root

- name: link OpenJ9 JDK 11
  file:
    src: /opt/jdk-11.0.3+7/
    dest: /opt/java-11-openj9-amd64
    state: link
  become: yes
  become_user: root
