---
# file: roles/java/tasks/main.yml

- name: download sdkman
  get_url:
    url: 'https://get.sdkman.io'
    dest: /root/sdkman.sh
  become: yes
  become_user: root

- name: set permissions on sdkman
  file:
    path: /root/sdkman.sh
    mode: 0755
  become: yes
  become_user: root

- name: install sdkman
  command: /root/sdkman.sh
  args:
    chdir: /root
    creates: /root/.sdkman
  become: true
  become_user: root
