---
# file: roles/java/tasks/main.yml

- name: download OpenJ9 JDK 14
  get_url:
    url: "https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14%2B36.1_openj9-0.19.0/OpenJDK14U-jdk_x64_linux_openj9_14_36_openj9-0.19.0.tar.gz"
    dest: "{{ ansible_env.HOME }}/Downloads/OpenJDK14U-jdk_x64_linux_openj9_14_36_openj9-0.19.0.tar.gz"

- name: unpack OpenJ9 JDK 14
  unarchive:
    src: "{{ ansible_env.HOME }}/Downloads/OpenJDK14U-jdk_x64_linux_openj9_14_36_openj9-0.19.0.tar.gz"
    dest: /opt/
    remote_src: yes
    creates: /opt/jdk-14+36/
  become: yes
  become_user: root

- name: link OpenJ9 JDK 11
  file:
    src: /opt/jdk-14+36/
    dest: /opt/java-14-openj9-amd64
    state: link
  become: yes
  become_user: root
