---
# roles/ubuntu/tasks/main.yml

- name: add PPAs
  apt_repository:
    repo: "{{ item.url }}"
    filename: "{{ item.name }}"
    state: present
    update_cache: no
  with_items:
    - "{{ repos[ansible_distribution_release] }}"
  when: 
    - repos[ansible_distribution_release] != None
    - repos[ansible_distribution_release] | length > 0
  become: true
  become_user: root

- name: update APT cache
  apt:
    upgrade: dist
    update_cache: yes
    state: latest
  become: true
  become_user: root

- name: install common packages
  apt:
    name: "{{ packages['common'] }}"
    state: latest
    allow_unauthenticated: yes
  become: true
  become_user: root

- name: install distro-specific packages
  apt:
    name: "{{ packages[ansible_distribution_release] }}"
    state: latest
    allow_unauthenticated: yes
  when: 
    - packages[ansible_distribution_release] != None
    - packages[ansible_distribution_release] | length > 0
  become: true
  become_user: root

#- name: remove packages
#  apt:
#    name: "{{ item }}"
#    state: absent
#    allow_unauthenticated: yes
#  with_items:
#    - "{{ remove_packages }}"
#  become: true
#  become_user: root

#- name: Infinality
#  replace:
#    dest: /etc/profile.d/infinality-settings.sh
#    regexp: '^USE_STYLE=.*'
#    replace: 'USE_STYLE="UBUNTU"'
#  become: true
#  become_user: root

#- name: make Gnome/Git keyring integration helper
#  command: make --directory=/usr/share/doc/git/contrib/credential/gnome-keyring
#  become: true
#  become_user: root

#- name: make Gnome/Git keyring integration helper
#  command: git config --global credential.helper /usr/share/doc/git/contrib/credential/gnome-keyring/git-credential-gnome-keyring

